# Generated by Django 6.0.4 on 2026-04-30 08:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logApi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, help_text='Hours already used in the current 70hr/8-day cycle.', max_digits=5)),
                ('departure_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('computed', 'Computed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('route_geojson', models.JSONField(blank=True, null=True)),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_driving_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='1-based day number within the trip.')),
                ('day_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logApi.daylog')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to='tripApi.trip')),
            ],
            options={
                'ordering': ['trip', 'day_number'],
                'unique_together': {('trip', 'day_log')},
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('fuel', 'Fuel Stop'), ('rest_break', '30-min Rest Break'), ('sleeper_break', '10-hr Sleeper Break'), ('dropoff', 'Dropoff')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('miles_from_prev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cumulative_miles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tripApi.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
    ]
