# Generated by Django 6.0.4 on 2026-04-30 08:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('from_location', models.TextField()),
                ('to_location', models.TextField()),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('main_office_address', models.TextField(blank=True)),
                ('home_terminal_address', models.TextField(blank=True)),
                ('total_miles_driven', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_mileage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_hours_driving', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_hours_on_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_hours_off_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_hours_sleeping', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('shipping_documents', models.TextField(blank=True)),
                ('dvl_or_manifest_no', models.CharField(blank=True, max_length=100)),
                ('shipper_commodity', models.CharField(blank=True, max_length=255)),
                ('co_driver_miles_driven', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_co_driver_entry', models.BooleanField(default=False)),
                ('co_driver_approved', models.BooleanField(blank=True, help_text='Null = pending, True = approved, False = rejected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_driver', models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driven_logs', to=settings.AUTH_USER_MODEL)),
                ('linked_primary_log', models.ForeignKey(blank=True, help_text="Set by a co-driver to link their log to the main driver's log.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver_submissions', to='logApi.daylog')),
                ('user', models.ForeignKey(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ActLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('OF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=2, verbose_name='Activity')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('day_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_logs', to='logApi.daylog')),
            ],
            options={
                'ordering': ['day_log', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='daylog',
            index=models.Index(fields=['user'], name='logApi_dayl_user_id_e27d06_idx'),
        ),
        migrations.AddIndex(
            model_name='daylog',
            index=models.Index(fields=['user', 'day'], name='logApi_dayl_user_id_19d5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='daylog',
            index=models.Index(fields=['day'], name='logApi_dayl_day_3d8f7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='daylog',
            unique_together={('user', 'day')},
        ),
        migrations.AddIndex(
            model_name='actlog',
            index=models.Index(fields=['day_log'], name='logApi_actl_day_log_a8c0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='actlog',
            index=models.Index(fields=['day_log', 'start_time'], name='logApi_actl_day_log_bd083c_idx'),
        ),
        migrations.AddConstraint(
            model_name='actlog',
            constraint=models.UniqueConstraint(fields=('day_log', 'start_time', 'end_time'), name='unique_actlog_per_range'),
        ),
        migrations.AddConstraint(
            model_name='actlog',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='actlog_start_before_end'),
        ),
    ]
